name: Build and Deploy React App to VPS

# Kích hoạt workflow khi có push vào nhánh 'main'
on:
  push:
    branches:
      - main # Thay đổi thành 'master' nếu bạn dùng nhánh đó

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Chạy trên máy ảo Ubuntu mới nhất của GitHub

    steps:
      # Bước 1: Checkout mã nguồn từ repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Chỉ định phiên bản Node.js khớp với dự án của bạn
          cache: 'npm' # Bật cache để tăng tốc độ cài đặt ở những lần chạy sau

      # Bước 3: Cài đặt các gói phụ thuộc và Build ứng dụng
      - name: Install and Build
        run: |
          npm install
          npm run build
        # Nếu bạn có biến môi trường cho lúc build (ví dụ: REACT_APP_API_URL)
        env:
          VITE_API_URL: ${{ env.VITE_API_URL }}

      # Bước 4: Deploy lên VPS qua SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }} # Lấy từ GitHub Secrets
          username: ${{ secrets.VPS_USERNAME }} # Lấy từ GitHub Secrets
          key: ${{ secrets.VPS_SSH_KEY }} # Lấy từ GitHub Secrets
          script: |
            # Sử dụng rsync để đồng bộ thư mục build vào VPS
            # -a: archive mode, giữ nguyên các thuộc tính file
            # -v: verbose, hiển thị chi tiết
            # -z: nén dữ liệu khi truyền
            # --delete: xóa các file ở đích không có ở nguồn
            rsync -avz --delete build/ /var/www/todoapp-web/
