name: Build and Deploy React App

# Kích hoạt workflow khi có push đến nhánh 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  #################################
  # GIAI ĐOẠN 1: BUILD ỨNG DỤNG  #
  #################################
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy mã nguồn từ repository về
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Node.js
      # 'node-version' nên khớp với phiên bản bạn dùng để phát triển
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Bật cache để tăng tốc độ cài đặt ở các lần chạy sau

      # Bước 3: Cài đặt các thư viện phụ thuộc
      # Dùng 'npm ci' thay vì 'npm install' để đảm bảo cài đặt chính xác từ file package-lock.json
      - name: Install dependencies
        run: npm ci

      # Bước 4: Build ứng dụng React
      # Lệnh này sẽ tạo thư mục 'build' chứa các file tĩnh
      # REACT_APP_API_URL là ví dụ về biến môi trường công khai cho React
      - name: Build React App
        run: npm run build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }} # Lấy từ Variables trong Settings, không phải Secret

      # Bước 5: Lưu lại thư mục 'build' để dùng cho job 'deploy'
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-app-build
          path: ./dist

  #################################
  # GIAI ĐOẠN 2: TRIỂN KHAI       #
  #################################
  deploy:
    # Job 'deploy' chỉ chạy sau khi job 'build' thành công
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Tải xuống thư mục 'dist' đã được lưu ở job trước
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-app-build
          path: ./dist

      # Bước 2: Deploy các file tĩnh lên máy chủ
      # Ví dụ này sử dụng SCP để sao chép thư mục 'build' đến máy chủ của bạn
      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}             # IP hoặc tên miền của máy chủ
          username: ${{ secrets.VPS_USERNAME }}     # Tên người dùng để đăng nhập SSH
          key: ${{ secrets.VPS_SSH_KEY }}       # Khóa riêng SSH để xác thực
          source: "./dist/*"                        # Sao chép toàn bộ nội dung trong thư mục 'build'
          target: "/var/www/todoapp-web"            # Thư mục đích trên máy chủ
          overwrite: true
